name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create public directory and copy files
      run: |
        mkdir -p public
        cp index.html public/
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo apt update
          
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            
            if ! command -v node &> /dev/null; then
              sudo apt-get install -y nodejs npm
            fi
          fi
          
          if ! command -v npm &> /dev/null; then
            sudo apt-get install -y npm
          fi
          
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          
          sudo mkdir -p /opt/webapps
          sudo chown $USER:$USER /opt/webapps
          
          sudo mkdir -p /var/log/pm2
          sudo chown $USER:$USER /var/log/pm2
          
          if [ ! -d "/opt/webapps/simple-tg-webapp" ]; then
            cd /opt/webapps
            git clone https://github.com/${{ github.repository }}.git simple-tg-webapp
          else
            cd /opt/webapps/simple-tg-webapp
            git fetch origin
            git reset --hard origin/main
          fi
          
          cd /opt/webapps/simple-tg-webapp
          npm ci --production
          mkdir -p public
          cp index.html public/
          
          if [ ! -f "ecosystem.config.js" ]; then
            cat > ecosystem.config.js << 'EOF'
          module.exports = {
            apps: [{
              name: 'simple-tg-webapp',
              script: 'server.js',
              cwd: '/opt/webapps/simple-tg-webapp',
              instances: 1,
              exec_mode: 'fork',
              env: {
                NODE_ENV: 'production',
                PORT: 3000
              },
              error_file: '/var/log/pm2/simple-tg-webapp-error.log',
              out_file: '/var/log/pm2/simple-tg-webapp-out.log',
              log_file: '/var/log/pm2/simple-tg-webapp.log',
              time: true
            }]
          }
          EOF
          fi
          
          if pm2 list | grep -q "simple-tg-webapp"; then
            pm2 restart simple-tg-webapp
          else
            pm2 start ecosystem.config.js
          fi
          
          pm2 save
          
          if ! systemctl is-enabled pm2-$USER &> /dev/null; then
            pm2 startup systemd -u $USER --hp $HOME
            sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u $USER --hp $HOME
          fi